---
- name: Enable intranet services
  hosts: all
  become: yes
  tasks:
    - name: firewalld remove access to httpd service
      firewalld:
        service: http
        permanent: true
        state: disabled
        immediate: yes

    - name: firewalld remove access to httpd service
      firewalld:
        service: https
        permanent: true
        state: disabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: false
        state: stopped
